// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: service.proto

package grpc_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShowIPService_GetClientIP_FullMethodName = "/showip.ShowIPService/GetClientIP"
)

// ShowIPServiceClient is the client API for ShowIPService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShowIPServiceClient interface {
	GetClientIP(ctx context.Context, in *ClientIPRequest, opts ...grpc.CallOption) (*ClientIPReply, error)
}

type showIPServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShowIPServiceClient(cc grpc.ClientConnInterface) ShowIPServiceClient {
	return &showIPServiceClient{cc}
}

func (c *showIPServiceClient) GetClientIP(ctx context.Context, in *ClientIPRequest, opts ...grpc.CallOption) (*ClientIPReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClientIPReply)
	err := c.cc.Invoke(ctx, ShowIPService_GetClientIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShowIPServiceServer is the server API for ShowIPService service.
// All implementations must embed UnimplementedShowIPServiceServer
// for forward compatibility.
type ShowIPServiceServer interface {
	GetClientIP(context.Context, *ClientIPRequest) (*ClientIPReply, error)
	mustEmbedUnimplementedShowIPServiceServer()
}

// UnimplementedShowIPServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShowIPServiceServer struct{}

func (UnimplementedShowIPServiceServer) GetClientIP(context.Context, *ClientIPRequest) (*ClientIPReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClientIP not implemented")
}
func (UnimplementedShowIPServiceServer) mustEmbedUnimplementedShowIPServiceServer() {}
func (UnimplementedShowIPServiceServer) testEmbeddedByValue()                       {}

// UnsafeShowIPServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShowIPServiceServer will
// result in compilation errors.
type UnsafeShowIPServiceServer interface {
	mustEmbedUnimplementedShowIPServiceServer()
}

func RegisterShowIPServiceServer(s grpc.ServiceRegistrar, srv ShowIPServiceServer) {
	// If the following call pancis, it indicates UnimplementedShowIPServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShowIPService_ServiceDesc, srv)
}

func _ShowIPService_GetClientIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShowIPServiceServer).GetClientIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShowIPService_GetClientIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShowIPServiceServer).GetClientIP(ctx, req.(*ClientIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShowIPService_ServiceDesc is the grpc.ServiceDesc for ShowIPService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShowIPService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "showip.ShowIPService",
	HandlerType: (*ShowIPServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetClientIP",
			Handler:    _ShowIPService_GetClientIP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
